language: php
sudo: required
dist: trusty
php:
  - '7.0'
  - '7.1'
#  - '7.2'
cache:
  directories:
    - $HOME/.composer/cache
env:
  - TEST_SUITE="vendor/bin/phpunit --coverage-clover coverage.xml"
  - TEST_SUITE="php artisan dusk"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS travis;'
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
  - cp .env.travis .env
  - composer install --no-interaction --prefer-dist --no-suggest --verbose
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan migrate --seed -v
  - php artisan serve > /dev/null 2>&1 &
script:
  - "$TEST_SUITE"
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  chrome: stable
  artifacts:
    working_dir: tests/Browser
    debug: true
notifications:
  email: false
  webhooks:
    urls:
      - https://misc.schrej.net/travistodiscord/pterodev.php
    on_success: change
    on_failure: always
    on_error: always
    on_cancel: always
    on_start: never
