version: '2'
services:
  database:
    hostname: database
    image: mariadb
    volumes:
      - "/srv/pterodactyl/database:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=apassword"
      - "MYSQL_DATABASE=pterodb"
      - "MYSQL_USER=ptero"
      - "MYSQL_PASSWORD=pterodbpass"

  cache:
    image: redis:alpine

  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025

  panel:
    image: quay.io/pterodactyl/panel:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - database
      - cache
      - mail
    volumes:
      - "/srv/pterodactyl/var/:/var/www/html/var/"
      - "/srv/pterodactyl/certs/:/root/.caddy/"
    environment:
      - "DB_HOST=database"
      - "DB_PORT=3306"
      - "DB_DATABASE=pterodb"
      - "DB_USERNAME=ptero"
      - "DB_PASSWORD=pterodbpass"
      - "APP_URL=http://localhost"
      - "APP_TIMEZONE=UTC"
      - "CACHE_DRIVER=redis"
      - "REDIS_HOST=cache"
      - "MAIL_DRIVER=smtp"
      - "MAIL_FROM=noreply@pterodactyl.io"
      - "MAIL_FROM_NAME='Pterodactyl Panel'"
      - "MAIL_USERNAME=''"
      - "MAIL_PASSWORD=''"
      - "MAIL_PORT=1025"
      - "MAIL_HOST=mail"
      - "MAIL_ENCRYPTION=false"
      - "ADMIN_EMAIL=admin@pterodactyl.io"
      - "ADMIN_PASS=Ptero123"
      - "ADMIN_USERNAME=admin"
      - "ADMIN_FIRSTNAME=Perry"
      - "ADMIN_LASTNAME=Dactyl"
      - "SSL=false"
